// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Message.proto

#pragma warning disable 1591, 0612, 3021
namespace Protocol.Transport
{

    [global::ProtoBuf.ProtoContract()]
    public partial class DataPackage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public DataPackage()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public MessageMajorType majorType { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public MessageMinorType minorType { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public byte[] data
        {
            get { return __pbn__data; }
            set { __pbn__data = value; }
        }
        public bool ShouldSerializedata()
        {
            return __pbn__data != null;
        }
        public void Resetdata()
        {
            __pbn__data = null;
        }
        private byte[] __pbn__data;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum MessageMajorType
    {
        Unknow = 0,
        Request = 1,
        Respond = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum MessageMinorType
    {
        Undefined = 0,
        LoginAuth = 1,
        Moving = 2,
        PlayerAppeared = 3,
        PlayerDisappeared = 4,
        Rotated = 5,
        Logout = 6,
    }

}

#pragma warning restore 1591, 0612, 3021
