// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: RespondMessages.proto

#pragma warning disable 1591, 0612, 3021
namespace Protocol.Respond
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Respond_LoginAuth : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Respond_LoginAuth()
        {
            neighborhood = new global::System.Collections.Generic.List<global::Protocol.RawData.PlayerInfo>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string token { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int sceneId { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public global::Protocol.RawData.PlayerInfo player { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<global::Protocol.RawData.PlayerInfo> neighborhood { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Respond_Logout : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Respond_Logout()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int pid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Respond_Moving : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Respond_Moving()
        {
            movementList = new global::System.Collections.Generic.List<global::Protocol.RawData.RespMovement>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<global::Protocol.RawData.RespMovement> movementList { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Respond_PlayerAppeared : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Respond_PlayerAppeared()
        {
            neighborhood = new global::System.Collections.Generic.List<global::Protocol.RawData.PlayerInfo>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<global::Protocol.RawData.PlayerInfo> neighborhood { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Respond_PlayerDisappeared : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Respond_PlayerDisappeared()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public int[] playerIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Respond_Rotated : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Respond_Rotated()
        {
            rotations = new global::System.Collections.Generic.List<global::Protocol.RawData.RespRotated>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<global::Protocol.RawData.RespRotated> rotations { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Respond_WorkSheet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Respond_WorkSheet()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public global::Protocol.DB.Table.WTI_Class_One data { get; set; }

    }

}

#pragma warning restore 1591, 0612, 3021
