// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: A.proto

#pragma warning disable 1591, 0612, 3021
namespace Tutorial
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Person : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Person()
        {
            Phones = new global::System.Collections.Generic.List<PhoneNumber>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"id", IsRequired = true)]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"email")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Email
        {
            get { return __pbn__Email ?? ""; }
            set { __pbn__Email = value; }
        }
        public bool ShouldSerializeEmail()
        {
            return __pbn__Email != null;
        }
        public void ResetEmail()
        {
            __pbn__Email = null;
        }
        private string __pbn__Email;

        [global::ProtoBuf.ProtoMember(4, Name = @"phone")]
        public global::System.Collections.Generic.List<PhoneNumber> Phones { get; private set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class PhoneNumber : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
            }
            public PhoneNumber()
            {
                OnConstructor();
            }

            partial void OnConstructor();

            [global::ProtoBuf.ProtoMember(1, Name = @"number", IsRequired = true)]
            public string Number { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"type")]
            [global::System.ComponentModel.DefaultValue(Person.PhoneType.Home)]
            public Person.PhoneType Type
            {
                get { return __pbn__Type ?? Person.PhoneType.Home; }
                set { __pbn__Type = value; }
            }
            public bool ShouldSerializeType()
            {
                return __pbn__Type != null;
            }
            public void ResetType()
            {
                __pbn__Type = null;
            }
            private Person.PhoneType? __pbn__Type;

        }

        [global::ProtoBuf.ProtoContract()]
        public enum PhoneType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"MOBILE")]
            Mobile = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"HOME")]
            Home = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"WORK")]
            Work = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AddressBook : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public AddressBook()
        {
            Persons = new global::System.Collections.Generic.List<Person>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"person")]
        public global::System.Collections.Generic.List<Person> Persons { get; private set; }

    }

}

#pragma warning restore 1591, 0612, 3021
