// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: A.proto

#pragma warning disable 1591, 0612, 3021
namespace tutorial
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Person : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Person()
        {
            phone = new global::System.Collections.Generic.List<PhoneNumber>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string name { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int id { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string email
        {
            get { return __pbn__email ?? ""; }
            set { __pbn__email = value; }
        }
        public bool ShouldSerializeemail()
        {
            return __pbn__email != null;
        }
        public void Resetemail()
        {
            __pbn__email = null;
        }
        private string __pbn__email;

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<PhoneNumber> phone { get; private set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class PhoneNumber : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
            }
            public PhoneNumber()
            {
                OnConstructor();
            }

            partial void OnConstructor();

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public string number { get; set; }

            [global::ProtoBuf.ProtoMember(2)]
            [global::System.ComponentModel.DefaultValue(Person.PhoneType.HOME)]
            public Person.PhoneType type
            {
                get { return __pbn__type ?? Person.PhoneType.HOME; }
                set { __pbn__type = value; }
            }
            public bool ShouldSerializetype()
            {
                return __pbn__type != null;
            }
            public void Resettype()
            {
                __pbn__type = null;
            }
            private Person.PhoneType? __pbn__type;

        }

        [global::ProtoBuf.ProtoContract()]
        public enum PhoneType
        {
            MOBILE = 0,
            HOME = 1,
            WORK = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AddressBook : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public AddressBook()
        {
            person = new global::System.Collections.Generic.List<Person>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<Person> person { get; private set; }

    }

}

#pragma warning restore 1591, 0612, 3021
