// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Login.proto

#pragma warning disable 1591, 0612, 3021
namespace Login
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Login : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Login()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string username { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string password { get; set; }

    }

}

#pragma warning restore 1591, 0612, 3021
