// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Messages.proto

#pragma warning disable 1591, 0612, 3021
namespace ProjectProtocal
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Message : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Message()
        {
            type = EMessageType.ERequest_LoginAuth;
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public EMessageType type { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public byte[] data
        {
            get { return __pbn__data; }
            set { __pbn__data = value; }
        }
        public bool ShouldSerializedata()
        {
            return __pbn__data != null;
        }
        public void Resetdata()
        {
            __pbn__data = null;
        }
        private byte[] __pbn__data;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Request_LoginAuth : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Request_LoginAuth()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string username { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string password { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Respond_LoginAuth : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Respond_LoginAuth()
        {
            neighborhood = new global::System.Collections.Generic.List<PlayerInfo>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string token { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int sceneId { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public PlayerInfo player { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<PlayerInfo> neighborhood { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Request_Logout : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Request_Logout()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int pid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Respond_Logout : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Respond_Logout()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int pid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Request_Moving : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Request_Moving()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public MovementData movement { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Respond_Moving : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Respond_Moving()
        {
            movementList = new global::System.Collections.Generic.List<RespMovement>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<RespMovement> movementList { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Respond_PlayerAppeared : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Respond_PlayerAppeared()
        {
            neighborhood = new global::System.Collections.Generic.List<PlayerInfo>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<PlayerInfo> neighborhood { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Respond_PlayerDisappeared : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Respond_PlayerDisappeared()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public int[] playerIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Request_Rotated : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Request_Rotated()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public Vector3 direction { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Respond_Rotated : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Respond_Rotated()
        {
            rotations = new global::System.Collections.Generic.List<RespRotated>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<RespRotated> rotations { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Vector3 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Vector3()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public float x { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public float y { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public float z { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public PlayerInfo()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int pid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string name { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public MovementData movement { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MovementData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MovementData()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public Vector3 position { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public Vector3 velocity { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RespMovement : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RespMovement()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int pid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public MovementData movement { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RespRotated : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RespRotated()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int pid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public Vector3 direction { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum EMessageType
    {
        ERequest_LoginAuth = 1,
        ERespond_LoginAuth = 2,
        ERequest_Moving = 3,
        ERespond_Moving = 4,
        ERespond_PlayerAppeared = 5,
        ERespond_PlayerDisappeared = 6,
        ERequest_Rotated = 7,
        ERespond_Rotated = 8,
        ERespond_Logout = 9,
    }

}

#pragma warning restore 1591, 0612, 3021
