# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RawData/InternalData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RawData/InternalData.proto',
  package='Protocal.RawData',
  serialized_pb=_b('\n\x1aRawData/InternalData.proto\x12\x10Protocal.RawData\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\x12\t\n\x01z\x18\x03 \x02(\x02\"Y\n\nPlayerInfo\x12\x0b\n\x03pid\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x30\n\x08movement\x18\x03 \x01(\x0b\x32\x1e.Protocal.RawData.MovementData\"h\n\x0cMovementData\x12+\n\x08position\x18\x01 \x01(\x0b\x32\x19.Protocal.RawData.Vector3\x12+\n\x08velocity\x18\x02 \x01(\x0b\x32\x19.Protocal.RawData.Vector3\"M\n\x0cRespMovement\x12\x0b\n\x03pid\x18\x01 \x02(\x05\x12\x30\n\x08movement\x18\x02 \x02(\x0b\x32\x1e.Protocal.RawData.MovementData\"H\n\x0bRespRotated\x12\x0b\n\x03pid\x18\x01 \x02(\x05\x12,\n\tdirection\x18\x02 \x02(\x0b\x32\x19.Protocal.RawData.Vector3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_VECTOR3 = _descriptor.Descriptor(
  name='Vector3',
  full_name='Protocal.RawData.Vector3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Protocal.RawData.Vector3.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='Protocal.RawData.Vector3.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='Protocal.RawData.Vector3.z', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=90,
)


_PLAYERINFO = _descriptor.Descriptor(
  name='PlayerInfo',
  full_name='Protocal.RawData.PlayerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='Protocal.RawData.PlayerInfo.pid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='Protocal.RawData.PlayerInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='movement', full_name='Protocal.RawData.PlayerInfo.movement', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=181,
)


_MOVEMENTDATA = _descriptor.Descriptor(
  name='MovementData',
  full_name='Protocal.RawData.MovementData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='Protocal.RawData.MovementData.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='Protocal.RawData.MovementData.velocity', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=287,
)


_RESPMOVEMENT = _descriptor.Descriptor(
  name='RespMovement',
  full_name='Protocal.RawData.RespMovement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='Protocal.RawData.RespMovement.pid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='movement', full_name='Protocal.RawData.RespMovement.movement', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=366,
)


_RESPROTATED = _descriptor.Descriptor(
  name='RespRotated',
  full_name='Protocal.RawData.RespRotated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='Protocal.RawData.RespRotated.pid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='direction', full_name='Protocal.RawData.RespRotated.direction', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=440,
)

_PLAYERINFO.fields_by_name['movement'].message_type = _MOVEMENTDATA
_MOVEMENTDATA.fields_by_name['position'].message_type = _VECTOR3
_MOVEMENTDATA.fields_by_name['velocity'].message_type = _VECTOR3
_RESPMOVEMENT.fields_by_name['movement'].message_type = _MOVEMENTDATA
_RESPROTATED.fields_by_name['direction'].message_type = _VECTOR3
DESCRIPTOR.message_types_by_name['Vector3'] = _VECTOR3
DESCRIPTOR.message_types_by_name['PlayerInfo'] = _PLAYERINFO
DESCRIPTOR.message_types_by_name['MovementData'] = _MOVEMENTDATA
DESCRIPTOR.message_types_by_name['RespMovement'] = _RESPMOVEMENT
DESCRIPTOR.message_types_by_name['RespRotated'] = _RESPROTATED

Vector3 = _reflection.GeneratedProtocolMessageType('Vector3', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR3,
  __module__ = 'RawData.InternalData_pb2'
  # @@protoc_insertion_point(class_scope:Protocal.RawData.Vector3)
  ))
_sym_db.RegisterMessage(Vector3)

PlayerInfo = _reflection.GeneratedProtocolMessageType('PlayerInfo', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERINFO,
  __module__ = 'RawData.InternalData_pb2'
  # @@protoc_insertion_point(class_scope:Protocal.RawData.PlayerInfo)
  ))
_sym_db.RegisterMessage(PlayerInfo)

MovementData = _reflection.GeneratedProtocolMessageType('MovementData', (_message.Message,), dict(
  DESCRIPTOR = _MOVEMENTDATA,
  __module__ = 'RawData.InternalData_pb2'
  # @@protoc_insertion_point(class_scope:Protocal.RawData.MovementData)
  ))
_sym_db.RegisterMessage(MovementData)

RespMovement = _reflection.GeneratedProtocolMessageType('RespMovement', (_message.Message,), dict(
  DESCRIPTOR = _RESPMOVEMENT,
  __module__ = 'RawData.InternalData_pb2'
  # @@protoc_insertion_point(class_scope:Protocal.RawData.RespMovement)
  ))
_sym_db.RegisterMessage(RespMovement)

RespRotated = _reflection.GeneratedProtocolMessageType('RespRotated', (_message.Message,), dict(
  DESCRIPTOR = _RESPROTATED,
  __module__ = 'RawData.InternalData_pb2'
  # @@protoc_insertion_point(class_scope:Protocal.RawData.RespRotated)
  ))
_sym_db.RegisterMessage(RespRotated)


# @@protoc_insertion_point(module_scope)
