# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Message.proto',
  package='Protocal.Message',
  serialized_pb=_b('\n\rMessage.proto\x12\x10Protocal.Message\"\x85\x01\n\x07Message\x12\x35\n\tMajorType\x18\x01 \x02(\x0e\x32\".Protocal.Message.MessageMajorType\x12\x35\n\tMinorType\x18\x02 \x02(\x0e\x32\".Protocal.Message.MessageMinorType\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c*,\n\x10MessageMajorType\x12\x0b\n\x07Request\x10\x01\x12\x0b\n\x07Respond\x10\x02*q\n\x10MessageMinorType\x12\r\n\tLoginAuth\x10\x01\x12\n\n\x06Moving\x10\x02\x12\x12\n\x0ePlayerAppeared\x10\x03\x12\x15\n\x11PlayerDisappeared\x10\x04\x12\x0b\n\x07Rotated\x10\x05\x12\n\n\x06Logout\x10\x06')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_MESSAGEMAJORTYPE = _descriptor.EnumDescriptor(
  name='MessageMajorType',
  full_name='Protocal.Message.MessageMajorType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Request', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Respond', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=171,
  serialized_end=215,
)
_sym_db.RegisterEnumDescriptor(_MESSAGEMAJORTYPE)

MessageMajorType = enum_type_wrapper.EnumTypeWrapper(_MESSAGEMAJORTYPE)
_MESSAGEMINORTYPE = _descriptor.EnumDescriptor(
  name='MessageMinorType',
  full_name='Protocal.Message.MessageMinorType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LoginAuth', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Moving', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PlayerAppeared', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PlayerDisappeared', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Rotated', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Logout', index=5, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=217,
  serialized_end=330,
)
_sym_db.RegisterEnumDescriptor(_MESSAGEMINORTYPE)

MessageMinorType = enum_type_wrapper.EnumTypeWrapper(_MESSAGEMINORTYPE)
Request = 1
Respond = 2
LoginAuth = 1
Moving = 2
PlayerAppeared = 3
PlayerDisappeared = 4
Rotated = 5
Logout = 6



_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='Protocal.Message.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MajorType', full_name='Protocal.Message.Message.MajorType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MinorType', full_name='Protocal.Message.Message.MinorType', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='Protocal.Message.Message.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=169,
)

_MESSAGE.fields_by_name['MajorType'].enum_type = _MESSAGEMAJORTYPE
_MESSAGE.fields_by_name['MinorType'].enum_type = _MESSAGEMINORTYPE
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.enum_types_by_name['MessageMajorType'] = _MESSAGEMAJORTYPE
DESCRIPTOR.enum_types_by_name['MessageMinorType'] = _MESSAGEMINORTYPE

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'Message_pb2'
  # @@protoc_insertion_point(class_scope:Protocal.Message.Message)
  ))
_sym_db.RegisterMessage(Message)


# @@protoc_insertion_point(module_scope)
