# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RequestMessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RawData.InternalData_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RequestMessages.proto',
  package='Protocal.Request',
  serialized_pb=_b('\n\x15RequestMessages.proto\x12\x10Protocal.Request\x1a\x1aRawData/InternalData.proto\"7\n\x11Request_LoginAuth\x12\x10\n\x08username\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\"\x1d\n\x0eRequest_Logout\x12\x0b\n\x03pid\x18\x01 \x02(\x05\"B\n\x0eRequest_Moving\x12\x30\n\x08movement\x18\x01 \x02(\x0b\x32\x1e.Protocal.RawData.MovementData\"?\n\x0fRequest_Rotated\x12,\n\tdirection\x18\x01 \x02(\x0b\x32\x19.Protocal.RawData.Vector3')
  ,
  dependencies=[RawData.InternalData_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REQUEST_LOGINAUTH = _descriptor.Descriptor(
  name='Request_LoginAuth',
  full_name='Protocal.Request.Request_LoginAuth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='Protocal.Request.Request_LoginAuth.username', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='Protocal.Request.Request_LoginAuth.password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=126,
)


_REQUEST_LOGOUT = _descriptor.Descriptor(
  name='Request_Logout',
  full_name='Protocal.Request.Request_Logout',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='Protocal.Request.Request_Logout.pid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=157,
)


_REQUEST_MOVING = _descriptor.Descriptor(
  name='Request_Moving',
  full_name='Protocal.Request.Request_Moving',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='movement', full_name='Protocal.Request.Request_Moving.movement', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=225,
)


_REQUEST_ROTATED = _descriptor.Descriptor(
  name='Request_Rotated',
  full_name='Protocal.Request.Request_Rotated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='direction', full_name='Protocal.Request.Request_Rotated.direction', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=290,
)

_REQUEST_MOVING.fields_by_name['movement'].message_type = RawData.InternalData_pb2._MOVEMENTDATA
_REQUEST_ROTATED.fields_by_name['direction'].message_type = RawData.InternalData_pb2._VECTOR3
DESCRIPTOR.message_types_by_name['Request_LoginAuth'] = _REQUEST_LOGINAUTH
DESCRIPTOR.message_types_by_name['Request_Logout'] = _REQUEST_LOGOUT
DESCRIPTOR.message_types_by_name['Request_Moving'] = _REQUEST_MOVING
DESCRIPTOR.message_types_by_name['Request_Rotated'] = _REQUEST_ROTATED

Request_LoginAuth = _reflection.GeneratedProtocolMessageType('Request_LoginAuth', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST_LOGINAUTH,
  __module__ = 'RequestMessages_pb2'
  # @@protoc_insertion_point(class_scope:Protocal.Request.Request_LoginAuth)
  ))
_sym_db.RegisterMessage(Request_LoginAuth)

Request_Logout = _reflection.GeneratedProtocolMessageType('Request_Logout', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST_LOGOUT,
  __module__ = 'RequestMessages_pb2'
  # @@protoc_insertion_point(class_scope:Protocal.Request.Request_Logout)
  ))
_sym_db.RegisterMessage(Request_Logout)

Request_Moving = _reflection.GeneratedProtocolMessageType('Request_Moving', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST_MOVING,
  __module__ = 'RequestMessages_pb2'
  # @@protoc_insertion_point(class_scope:Protocal.Request.Request_Moving)
  ))
_sym_db.RegisterMessage(Request_Moving)

Request_Rotated = _reflection.GeneratedProtocolMessageType('Request_Rotated', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST_ROTATED,
  __module__ = 'RequestMessages_pb2'
  # @@protoc_insertion_point(class_scope:Protocal.Request.Request_Rotated)
  ))
_sym_db.RegisterMessage(Request_Rotated)


# @@protoc_insertion_point(module_scope)
