# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RespondMessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from RawData import InternalData_pb2 as RawData_dot_InternalData__pb2
from RawData import WorkTicketInformation_pb2 as RawData_dot_WorkTicketInformation__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RespondMessages.proto',
  package='Protocol.Respond',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x15RespondMessages.proto\x12\x10Protocol.Respond\x1a\x1aRawData/InternalData.proto\x1a#RawData/WorkTicketInformation.proto\"\x95\x01\n\x11Respond_LoginAuth\x12\r\n\x05token\x18\x01 \x02(\t\x12\x0f\n\x07sceneId\x18\x02 \x02(\x05\x12,\n\x06player\x18\x03 \x02(\x0b\x32\x1c.Protocol.RawData.PlayerInfo\x12\x32\n\x0cneighborhood\x18\x04 \x03(\x0b\x32\x1c.Protocol.RawData.PlayerInfo\"\x1d\n\x0eRespond_Logout\x12\x0b\n\x03pid\x18\x01 \x02(\x05\"F\n\x0eRespond_Moving\x12\x34\n\x0cmovementList\x18\x01 \x03(\x0b\x32\x1e.Protocol.RawData.RespMovement\"L\n\x16Respond_PlayerAppeared\x12\x32\n\x0cneighborhood\x18\x01 \x03(\x0b\x32\x1c.Protocol.RawData.PlayerInfo\".\n\x19Respond_PlayerDisappeared\x12\x11\n\tplayerIds\x18\x01 \x03(\x05\"C\n\x0fRespond_Rotated\x12\x30\n\trotations\x18\x01 \x03(\x0b\x32\x1d.Protocol.RawData.RespRotated\"C\n\x11Respond_WorkSheet\x12.\n\x04\x64\x61ta\x18\x01 \x02(\x0b\x32 .Protocol.DB.Table.WTI_Class_One')
  ,
  dependencies=[RawData_dot_InternalData__pb2.DESCRIPTOR,RawData_dot_WorkTicketInformation__pb2.DESCRIPTOR,])




_RESPOND_LOGINAUTH = _descriptor.Descriptor(
  name='Respond_LoginAuth',
  full_name='Protocol.Respond.Respond_LoginAuth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='Protocol.Respond.Respond_LoginAuth.token', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sceneId', full_name='Protocol.Respond.Respond_LoginAuth.sceneId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player', full_name='Protocol.Respond.Respond_LoginAuth.player', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='neighborhood', full_name='Protocol.Respond.Respond_LoginAuth.neighborhood', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=258,
)


_RESPOND_LOGOUT = _descriptor.Descriptor(
  name='Respond_Logout',
  full_name='Protocol.Respond.Respond_Logout',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='Protocol.Respond.Respond_Logout.pid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=289,
)


_RESPOND_MOVING = _descriptor.Descriptor(
  name='Respond_Moving',
  full_name='Protocol.Respond.Respond_Moving',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='movementList', full_name='Protocol.Respond.Respond_Moving.movementList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=361,
)


_RESPOND_PLAYERAPPEARED = _descriptor.Descriptor(
  name='Respond_PlayerAppeared',
  full_name='Protocol.Respond.Respond_PlayerAppeared',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='neighborhood', full_name='Protocol.Respond.Respond_PlayerAppeared.neighborhood', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=439,
)


_RESPOND_PLAYERDISAPPEARED = _descriptor.Descriptor(
  name='Respond_PlayerDisappeared',
  full_name='Protocol.Respond.Respond_PlayerDisappeared',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerIds', full_name='Protocol.Respond.Respond_PlayerDisappeared.playerIds', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=441,
  serialized_end=487,
)


_RESPOND_ROTATED = _descriptor.Descriptor(
  name='Respond_Rotated',
  full_name='Protocol.Respond.Respond_Rotated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rotations', full_name='Protocol.Respond.Respond_Rotated.rotations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=489,
  serialized_end=556,
)


_RESPOND_WORKSHEET = _descriptor.Descriptor(
  name='Respond_WorkSheet',
  full_name='Protocol.Respond.Respond_WorkSheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='Protocol.Respond.Respond_WorkSheet.data', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=558,
  serialized_end=625,
)

_RESPOND_LOGINAUTH.fields_by_name['player'].message_type = RawData_dot_InternalData__pb2._PLAYERINFO
_RESPOND_LOGINAUTH.fields_by_name['neighborhood'].message_type = RawData_dot_InternalData__pb2._PLAYERINFO
_RESPOND_MOVING.fields_by_name['movementList'].message_type = RawData_dot_InternalData__pb2._RESPMOVEMENT
_RESPOND_PLAYERAPPEARED.fields_by_name['neighborhood'].message_type = RawData_dot_InternalData__pb2._PLAYERINFO
_RESPOND_ROTATED.fields_by_name['rotations'].message_type = RawData_dot_InternalData__pb2._RESPROTATED
_RESPOND_WORKSHEET.fields_by_name['data'].message_type = RawData_dot_WorkTicketInformation__pb2._WTI_CLASS_ONE
DESCRIPTOR.message_types_by_name['Respond_LoginAuth'] = _RESPOND_LOGINAUTH
DESCRIPTOR.message_types_by_name['Respond_Logout'] = _RESPOND_LOGOUT
DESCRIPTOR.message_types_by_name['Respond_Moving'] = _RESPOND_MOVING
DESCRIPTOR.message_types_by_name['Respond_PlayerAppeared'] = _RESPOND_PLAYERAPPEARED
DESCRIPTOR.message_types_by_name['Respond_PlayerDisappeared'] = _RESPOND_PLAYERDISAPPEARED
DESCRIPTOR.message_types_by_name['Respond_Rotated'] = _RESPOND_ROTATED
DESCRIPTOR.message_types_by_name['Respond_WorkSheet'] = _RESPOND_WORKSHEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Respond_LoginAuth = _reflection.GeneratedProtocolMessageType('Respond_LoginAuth', (_message.Message,), dict(
  DESCRIPTOR = _RESPOND_LOGINAUTH,
  __module__ = 'RespondMessages_pb2'
  # @@protoc_insertion_point(class_scope:Protocol.Respond.Respond_LoginAuth)
  ))
_sym_db.RegisterMessage(Respond_LoginAuth)

Respond_Logout = _reflection.GeneratedProtocolMessageType('Respond_Logout', (_message.Message,), dict(
  DESCRIPTOR = _RESPOND_LOGOUT,
  __module__ = 'RespondMessages_pb2'
  # @@protoc_insertion_point(class_scope:Protocol.Respond.Respond_Logout)
  ))
_sym_db.RegisterMessage(Respond_Logout)

Respond_Moving = _reflection.GeneratedProtocolMessageType('Respond_Moving', (_message.Message,), dict(
  DESCRIPTOR = _RESPOND_MOVING,
  __module__ = 'RespondMessages_pb2'
  # @@protoc_insertion_point(class_scope:Protocol.Respond.Respond_Moving)
  ))
_sym_db.RegisterMessage(Respond_Moving)

Respond_PlayerAppeared = _reflection.GeneratedProtocolMessageType('Respond_PlayerAppeared', (_message.Message,), dict(
  DESCRIPTOR = _RESPOND_PLAYERAPPEARED,
  __module__ = 'RespondMessages_pb2'
  # @@protoc_insertion_point(class_scope:Protocol.Respond.Respond_PlayerAppeared)
  ))
_sym_db.RegisterMessage(Respond_PlayerAppeared)

Respond_PlayerDisappeared = _reflection.GeneratedProtocolMessageType('Respond_PlayerDisappeared', (_message.Message,), dict(
  DESCRIPTOR = _RESPOND_PLAYERDISAPPEARED,
  __module__ = 'RespondMessages_pb2'
  # @@protoc_insertion_point(class_scope:Protocol.Respond.Respond_PlayerDisappeared)
  ))
_sym_db.RegisterMessage(Respond_PlayerDisappeared)

Respond_Rotated = _reflection.GeneratedProtocolMessageType('Respond_Rotated', (_message.Message,), dict(
  DESCRIPTOR = _RESPOND_ROTATED,
  __module__ = 'RespondMessages_pb2'
  # @@protoc_insertion_point(class_scope:Protocol.Respond.Respond_Rotated)
  ))
_sym_db.RegisterMessage(Respond_Rotated)

Respond_WorkSheet = _reflection.GeneratedProtocolMessageType('Respond_WorkSheet', (_message.Message,), dict(
  DESCRIPTOR = _RESPOND_WORKSHEET,
  __module__ = 'RespondMessages_pb2'
  # @@protoc_insertion_point(class_scope:Protocol.Respond.Respond_WorkSheet)
  ))
_sym_db.RegisterMessage(Respond_WorkSheet)


# @@protoc_insertion_point(module_scope)
