// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: InternalData.proto

#pragma warning disable 1591, 0612, 3021
namespace Protocol.RawData
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Vector3 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Vector3()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public float x { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public float y { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public float z { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public PlayerInfo()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int pid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string name { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public PlayerType playerType { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public MovementData movement { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MovementData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MovementData()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public Vector3 position { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public Vector3 velocity { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RespMovement : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RespMovement()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int pid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public MovementData movement { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RespRotated : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RespRotated()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int pid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public Vector3 direction { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum PlayerType
    {
        EPT_HUMAN = 0,
        EPT_ROBOT = 1,
        EPT_UAV = 2,
    }

}

#pragma warning restore 1591, 0612, 3021
