// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: WorkTicketInformation.proto

#pragma warning disable 1591, 0612, 3021
namespace Protocol.DB.Table
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Date : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Date()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int year { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int month { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int day { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int hour { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public int minute { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public int second { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WTI_Class_One : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public WTI_Class_One()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string WORK_WRITE_ID { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string WORK_WRITE_NO { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string WHETHER_EXTERIOR { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public string WORKBILL { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public string TDSQD { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public string DH_WRITE_NO { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public string DH_WRITE_NAME { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public string WORK_PRINCIPAL_NAME { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public string PLAN_BEGIN_DATE { get; set; }

        [global::ProtoBuf.ProtoMember(10, IsRequired = true)]
        public string DEPARTMENT_ID { get; set; }

        [global::ProtoBuf.ProtoMember(11, IsRequired = true)]
        public string DEPARTMENT_NAME { get; set; }

        [global::ProtoBuf.ProtoMember(12, IsRequired = true)]
        public string CZ_TYPE { get; set; }

        [global::ProtoBuf.ProtoMember(13, IsRequired = true)]
        public string CZ_TYPE_NO { get; set; }

        [global::ProtoBuf.ProtoMember(14, IsRequired = true)]
        public string CZ_ID { get; set; }

        [global::ProtoBuf.ProtoMember(15, IsRequired = true)]
        public string CZ_NAME { get; set; }

        [global::ProtoBuf.ProtoMember(16, IsRequired = true)]
        public string YWDW_ID { get; set; }

        [global::ProtoBuf.ProtoMember(17, IsRequired = true)]
        public string YWDW_NAME { get; set; }

        [global::ProtoBuf.ProtoMember(18, IsRequired = true)]
        public string WORK_PRINCIPAL_ID { get; set; }

        [global::ProtoBuf.ProtoMember(19, IsRequired = true)]
        public string WORK_MOBILE_PHONE { get; set; }

        [global::ProtoBuf.ProtoMember(20, IsRequired = true)]
        public string PLAN_END_TIME { get; set; }

        [global::ProtoBuf.ProtoMember(21, IsRequired = true)]
        public string WORK_PERSONNEL { get; set; }

        [global::ProtoBuf.ProtoMember(22, IsRequired = true)]
        public string WORK_PERSONNEL_COUNT { get; set; }

        [global::ProtoBuf.ProtoMember(23, IsRequired = true)]
        public string WORK_TASK { get; set; }

        [global::ProtoBuf.ProtoMember(24, IsRequired = true)]
        public string WORK_PLACE { get; set; }

        [global::ProtoBuf.ProtoMember(25, IsRequired = true)]
        public string ZDZZJHR_ID { get; set; }

        [global::ProtoBuf.ProtoMember(26, IsRequired = true)]
        public string ZDZZJHR_NAME { get; set; }

        [global::ProtoBuf.ProtoMember(27, IsRequired = true)]
        public string YLDLQ { get; set; }

        [global::ProtoBuf.ProtoMember(28, IsRequired = true)]
        public string YLGLKG { get; set; }

        [global::ProtoBuf.ProtoMember(29, IsRequired = true)]
        public string YTQXGZLDY_DY_ECHL { get; set; }

        [global::ProtoBuf.ProtoMember(30, IsRequired = true)]
        public string YHJDDZ_ZSJDX_YSJYDB { get; set; }

        [global::ProtoBuf.ProtoMember(31, IsRequired = true)]
        public string YSZD_YGBSP { get; set; }

        [global::ProtoBuf.ProtoMember(32, IsRequired = true)]
        public string QTAQCS_ZYSX { get; set; }

        [global::ProtoBuf.ProtoMember(33, IsRequired = true)]
        public string IS_XLDCJD { get; set; }

        [global::ProtoBuf.ProtoMember(34, IsRequired = true)]
        public string IS_COMMUNICATION { get; set; }

        [global::ProtoBuf.ProtoMember(35, IsRequired = true)]
        public string ECCSD_NUM { get; set; }

        [global::ProtoBuf.ProtoMember(36, IsRequired = true)]
        public string UNDERWRITE { get; set; }

        [global::ProtoBuf.ProtoMember(37, IsRequired = true)]
        public string SIGN_TIME { get; set; }

        [global::ProtoBuf.ProtoMember(38, IsRequired = true)]
        public string UNDERWRITE_NAME { get; set; }

        [global::ProtoBuf.ProtoMember(39, IsRequired = true)]
        public string UNDERWRITE_SIGNATURE { get; set; }

        [global::ProtoBuf.ProtoMember(40, IsRequired = true)]
        public string CHECK_TIME { get; set; }

        [global::ProtoBuf.ProtoMember(41, IsRequired = true)]
        public string UNDERWRITE_SIGNATURE_NAME { get; set; }

        [global::ProtoBuf.ProtoMember(42, IsRequired = true)]
        public string WORK_PRIME_ID { get; set; }

        [global::ProtoBuf.ProtoMember(43, IsRequired = true)]
        public string WORK_PRIME_NAME { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WTI_Class_Two : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public WTI_Class_Two()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string WORK_WRITE_ID { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string WORK_WRITE_NO { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string WHETHER_EXTERIOR { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public string WORKBILL { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public string DH_WRITE_NO { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public string DH_WRITE_NAME { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public bool IS_COMMUNICATION_TICKET { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public string DEPARTMENT_NAME { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public string SUBSTATION_TYPE { get; set; }

        [global::ProtoBuf.ProtoMember(10, IsRequired = true)]
        public string SUBSTATION_ID { get; set; }

        [global::ProtoBuf.ProtoMember(11, IsRequired = true)]
        public string SUBSTATION_NAME { get; set; }

        [global::ProtoBuf.ProtoMember(12, IsRequired = true)]
        public string OPERATION_UNIT { get; set; }

        [global::ProtoBuf.ProtoMember(13, IsRequired = true)]
        public string WORK_MASTER_UID { get; set; }

        [global::ProtoBuf.ProtoMember(14, IsRequired = true)]
        public string WORK_MASTER_UNAME { get; set; }

        [global::ProtoBuf.ProtoMember(15, IsRequired = true)]
        public string WORK_MASTER_UPHONE { get; set; }

        [global::ProtoBuf.ProtoMember(16, IsRequired = true)]
        public Date PLAN_BEGIN_DATE { get; set; }

        [global::ProtoBuf.ProtoMember(17, IsRequired = true)]
        public Date PLAN_END_TIME { get; set; }

        [global::ProtoBuf.ProtoMember(18, IsRequired = true)]
        public string WORK_MEMBER { get; set; }

        [global::ProtoBuf.ProtoMember(19, IsRequired = true)]
        public string WORK_TASK { get; set; }

        [global::ProtoBuf.ProtoMember(20, IsRequired = true)]
        public string WORK_PLACE { get; set; }

        [global::ProtoBuf.ProtoMember(21, IsRequired = true)]
        public string HIGHP_DEVICE_STATE { get; set; }

        [global::ProtoBuf.ProtoMember(22, IsRequired = true)]
        public string POWER_CIRCLE_STATE { get; set; }

        [global::ProtoBuf.ProtoMember(23, IsRequired = true)]
        public string DCPOWER_LOWP_CIRCLE { get; set; }

        [global::ProtoBuf.ProtoMember(24, IsRequired = true)]
        public string BILLBOARD { get; set; }

        [global::ProtoBuf.ProtoMember(25, IsRequired = true)]
        public string OTHER_CARE { get; set; }

        [global::ProtoBuf.ProtoMember(26, IsRequired = true)]
        public string IS_SECONDBILL { get; set; }

        [global::ProtoBuf.ProtoMember(27, IsRequired = true)]
        public string SECONDBILL_COUNT { get; set; }

        [global::ProtoBuf.ProtoMember(28, IsRequired = true)]
        public string TICKET_SIGN_UID { get; set; }

        [global::ProtoBuf.ProtoMember(29, IsRequired = true)]
        public string TICKET_SIGN_UNAME { get; set; }

        [global::ProtoBuf.ProtoMember(30, IsRequired = true)]
        public Date TICKET_CREAT_TIME { get; set; }

        [global::ProtoBuf.ProtoMember(31, IsRequired = true)]
        public string WATCH_UID { get; set; }

        [global::ProtoBuf.ProtoMember(32, IsRequired = true)]
        public string WATCH_UNAME { get; set; }

        [global::ProtoBuf.ProtoMember(33, IsRequired = true)]
        public Date RECEIVE_TIME { get; set; }

        [global::ProtoBuf.ProtoMember(34, IsRequired = true)]
        public bool WHETHER_MEET_SAFTY { get; set; }

        [global::ProtoBuf.ProtoMember(35, IsRequired = true)]
        public string SUPPLEMENT_SAFTY { get; set; }

        [global::ProtoBuf.ProtoMember(36, IsRequired = true)]
        public string ELE_GENERATRIX_WIRE { get; set; }

        [global::ProtoBuf.ProtoMember(37, IsRequired = true)]
        public string ELE_SWITCH { get; set; }

        [global::ProtoBuf.ProtoMember(38, IsRequired = true)]
        public string ELE_PART { get; set; }

        [global::ProtoBuf.ProtoMember(39, IsRequired = true)]
        public string PERMISSION_OTHER_CARE { get; set; }

        [global::ProtoBuf.ProtoMember(40, IsRequired = true)]
        public Date PERMISSION_TIME { get; set; }

        [global::ProtoBuf.ProtoMember(41, IsRequired = true)]
        public string WORK_PERMISSION_UID { get; set; }

        [global::ProtoBuf.ProtoMember(42, IsRequired = true)]
        public string WORK_PERMISSION_UNME { get; set; }

        [global::ProtoBuf.ProtoMember(43, IsRequired = true)]
        public Date WORK_END_TIME { get; set; }

        [global::ProtoBuf.ProtoMember(44, IsRequired = true)]
        public string CHANGE_SIGN_UID { get; set; }

        [global::ProtoBuf.ProtoMember(45, IsRequired = true)]
        public string CHANGE_SIGN_UNAME { get; set; }

        [global::ProtoBuf.ProtoMember(46, IsRequired = true)]
        public string CHANGE_PRINCIPAL_UID { get; set; }

        [global::ProtoBuf.ProtoMember(47, IsRequired = true)]
        public string CHANGE_PRINCIPAL_UNAME { get; set; }

        [global::ProtoBuf.ProtoMember(48, IsRequired = true)]
        public string CHANGE_NEW_PRINCIPAL_UID { get; set; }

        [global::ProtoBuf.ProtoMember(49, IsRequired = true)]
        public string CHANGE_NEW_PRINCIPAL_UNAME { get; set; }

        [global::ProtoBuf.ProtoMember(50, IsRequired = true)]
        public string ADD_CONTENT_PERMISSION_UID { get; set; }

        [global::ProtoBuf.ProtoMember(51, IsRequired = true)]
        public string ADD_CONTENT_PERMISSION_UNAME { get; set; }

        [global::ProtoBuf.ProtoMember(52, IsRequired = true)]
        public Date CHANGE_TIME { get; set; }

        [global::ProtoBuf.ProtoMember(53, IsRequired = true)]
        public Date DELAY_TIME { get; set; }

        [global::ProtoBuf.ProtoMember(54, IsRequired = true)]
        public Date WRITE_TIME { get; set; }

        [global::ProtoBuf.ProtoMember(55, IsRequired = true)]
        public string ADD_CONTENT_DETAIL { get; set; }

        [global::ProtoBuf.ProtoMember(56, IsRequired = true)]
        public string ADD_CONTENT_DETAIL_TIME { get; set; }

        [global::ProtoBuf.ProtoMember(57, IsRequired = true)]
        public Date SAFE_GIVE_TIME { get; set; }

        [global::ProtoBuf.ProtoMember(58, IsRequired = true)]
        public string WHETHER_QUALIFIED { get; set; }

        [global::ProtoBuf.ProtoMember(59, IsRequired = true)]
        public string REMAKE { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WTI_Class_Three : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public WTI_Class_Three()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string WORK_WRITE_ID { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string WORK_WRITE_NO { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string WHETHER_EXTERIOR { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public string WORKBILL { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public string DH_WRITE_NO { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public string DH_WRITE_NAME { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public string DEPARTMENT_NAME { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public string SUBSTATION_TYPE { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public string SUBSTATION_ID { get; set; }

        [global::ProtoBuf.ProtoMember(10, IsRequired = true)]
        public string SUBSTATION_NAME { get; set; }

        [global::ProtoBuf.ProtoMember(11, IsRequired = true)]
        public string OPERATION_UNIT { get; set; }

        [global::ProtoBuf.ProtoMember(12, IsRequired = true)]
        public string WORK_MASTER_UID { get; set; }

        [global::ProtoBuf.ProtoMember(13, IsRequired = true)]
        public string WORK_MASTER_UNAME { get; set; }

        [global::ProtoBuf.ProtoMember(14, IsRequired = true)]
        public string WORK_MASTER_UPHONE { get; set; }

        [global::ProtoBuf.ProtoMember(15, IsRequired = true)]
        public Date PLAN_BEGIN_DATE { get; set; }

        [global::ProtoBuf.ProtoMember(16, IsRequired = true)]
        public Date PLAN_END_TIME { get; set; }

        [global::ProtoBuf.ProtoMember(17, IsRequired = true)]
        public string WORK_MEMBER { get; set; }

        [global::ProtoBuf.ProtoMember(18, IsRequired = true)]
        public string WORK_TASK { get; set; }

        [global::ProtoBuf.ProtoMember(19, IsRequired = true)]
        public string WORK_PLACE { get; set; }

        [global::ProtoBuf.ProtoMember(20, IsRequired = true)]
        public string SAFTY_AND_CARE { get; set; }

        [global::ProtoBuf.ProtoMember(21, IsRequired = true)]
        public string WATCH_UID { get; set; }

        [global::ProtoBuf.ProtoMember(22, IsRequired = true)]
        public string WATCH_UNAME { get; set; }

        [global::ProtoBuf.ProtoMember(23, IsRequired = true)]
        public Date RECEIVE_TIME { get; set; }

        [global::ProtoBuf.ProtoMember(24, IsRequired = true)]
        public bool WHETHER_MEET_SAFTY { get; set; }

        [global::ProtoBuf.ProtoMember(25, IsRequired = true)]
        public string SUPPLEMENT_SAFTY { get; set; }

        [global::ProtoBuf.ProtoMember(26, IsRequired = true)]
        public string ELE_GENERATRIX_WIRE { get; set; }

        [global::ProtoBuf.ProtoMember(27, IsRequired = true)]
        public string ELE_SWITCH { get; set; }

        [global::ProtoBuf.ProtoMember(28, IsRequired = true)]
        public string ELE_PART { get; set; }

        [global::ProtoBuf.ProtoMember(29, IsRequired = true)]
        public string PERMISSION_OTHER_CARE { get; set; }

        [global::ProtoBuf.ProtoMember(30, IsRequired = true)]
        public Date PERMISSION_TIME { get; set; }

        [global::ProtoBuf.ProtoMember(31, IsRequired = true)]
        public string WORK_PERMISSION_UID { get; set; }

        [global::ProtoBuf.ProtoMember(32, IsRequired = true)]
        public string WORK_PERMISSION_UNME { get; set; }

        [global::ProtoBuf.ProtoMember(33, IsRequired = true)]
        public Date WORK_END_TIME { get; set; }

        [global::ProtoBuf.ProtoMember(34, IsRequired = true)]
        public string CHANGE_SIGN_UID { get; set; }

        [global::ProtoBuf.ProtoMember(35, IsRequired = true)]
        public string CHANGE_SIGN_UNAME { get; set; }

        [global::ProtoBuf.ProtoMember(36, IsRequired = true)]
        public string CHANGE_PRINCIPAL_UID { get; set; }

        [global::ProtoBuf.ProtoMember(37, IsRequired = true)]
        public string CHANGE_PRINCIPAL_UNAME { get; set; }

        [global::ProtoBuf.ProtoMember(38, IsRequired = true)]
        public string CHANGE_NEW_PRINCIPAL_UID { get; set; }

        [global::ProtoBuf.ProtoMember(39, IsRequired = true)]
        public string CHANGE_NEW_PRINCIPAL_UNAME { get; set; }

        [global::ProtoBuf.ProtoMember(40, IsRequired = true)]
        public string ADD_CONTENT_PERMISSION_UID { get; set; }

        [global::ProtoBuf.ProtoMember(41, IsRequired = true)]
        public string ADD_CONTENT_PERMISSION_UNAME { get; set; }

        [global::ProtoBuf.ProtoMember(42, IsRequired = true)]
        public Date CHANGE_TIME { get; set; }

        [global::ProtoBuf.ProtoMember(43, IsRequired = true)]
        public Date DELAY_TIME { get; set; }

        [global::ProtoBuf.ProtoMember(44, IsRequired = true)]
        public Date WRITE_TIME { get; set; }

        [global::ProtoBuf.ProtoMember(45, IsRequired = true)]
        public string ADD_CONTENT_DETAIL { get; set; }

        [global::ProtoBuf.ProtoMember(46, IsRequired = true)]
        public Date ADD_CONTENT_DETAIL_TIME { get; set; }

        [global::ProtoBuf.ProtoMember(47, IsRequired = true)]
        public Date SAFE_GIVE_TIME { get; set; }

        [global::ProtoBuf.ProtoMember(48, IsRequired = true)]
        public bool WHETHER_QUALIFIED { get; set; }

        [global::ProtoBuf.ProtoMember(49, IsRequired = true)]
        public string REMAKE { get; set; }

    }

}

#pragma warning restore 1591, 0612, 3021
